<?php

declare(strict_types=1);

namespace KaririCode\Devkit\Configuration;

use KaririCode\Devkit\Contract\ConfigGenerator;
use KaririCode\Devkit\Core\ProjectContext;

/**
 * Generates `.kcode/php-cs-fixer.php`.
 *
 * KaririCode coding style: PSR-12 + PHP 8.4 migration + strict types +
 * compiler-optimized native function invocations.
 *
 * @since 1.0.0
 */
final class CsFixerConfigGenerator implements ConfigGenerator
{
    #[\Override]
    public function toolName(): string
    {
        return 'cs-fixer';
    }

    #[\Override]
    public function outputPath(): string
    {
        return 'php-cs-fixer.php';
    }

    #[\Override]
    public function generate(ProjectContext $context): string
    {
        $finderDirs = '';

        foreach ($context->relativeSourceDirs() as $dir) {
            $finderDirs .= "    ->in(__DIR__ . '/../{$dir}')\n";
        }

        foreach ($context->relativeTestDirs() as $dir) {
            $finderDirs .= "    ->in(__DIR__ . '/../{$dir}')\n";
        }

        $rulesExport = $this->exportRules($context->csFixerRules);

        return <<<PHP
            <?php

            declare(strict_types=1);

            /**
             * Generated by KaririCode Devkit — override rules via devkit.php (project root)
             * key: cs_fixer_rules (merged with KaririCode defaults).
             */

            \$finder = PhpCsFixer\\Finder::create()
            {$finderDirs}    ->name('*.php')
                ->ignoreDotFiles(true)
                ->ignoreVCS(true);

            return (new PhpCsFixer\\Config())
                ->setRules({$rulesExport})
                ->setFinder(\$finder)
                ->setRiskyAllowed(true)
                ->setUsingCache(true)
                ->setCacheFile(__DIR__ . '/build/.php-cs-fixer.cache');

            PHP;
    }

    /** @param array<string, mixed> $rules */
    private function exportRules(array $rules): string
    {
        $export = var_export($rules, true);

        // Normalize var_export output to short array syntax
        $export = (string) preg_replace('/^array \($/m', '[', $export);
        $export = (string) preg_replace('/^\)$/m', ']', $export);
        $export = str_replace('array (', '[', $export);
        $export = str_replace(')', ']', $export);

        return $export;
    }
}
