<?php

declare(strict_types=1);

namespace KaririCode\Devkit\Configuration;

use KaririCode\Devkit\Contract\ConfigGenerator;
use KaririCode\Devkit\Core\ProjectContext;

/**
 * Generates `.kcode/phpstan.neon`.
 *
 * @since 1.0.0
 */
final class PhpStanConfigGenerator implements ConfigGenerator
{
    public function toolName(): string
    {
        return 'phpstan';
    }

    public function outputPath(): string
    {
        return 'phpstan.neon';
    }

    public function generate(ProjectContext $context): string
    {
        $paths = \implode("\n", \array_map(
            static fn (string $d): string => "        - ../{$d}",
            $context->relativeSourceDirs(),
        ));

        $excludes = '';
        if ([] !== $context->excludeDirs) {
            $items = \implode("\n", \array_map(
                static fn (string $d): string => "        - ../{$d}",
                $context->excludeDirs,
            ));
            $excludes = <<<NEON

    excludePaths:
{$items}
NEON;
        }

        return <<<NEON
# Generated by KaririCode Devkit — override via devkit.php (project root)
parameters:
    level: {$context->phpstanLevel}
    paths:
{$paths}
{$excludes}
    tmpDir: build/.phpstan
    checkMissingIterableValueType: true
    checkGenericClassInNonGenericObjectType: true
    checkMissingCallableSignature: true
    treatPhpDocTypesAsCertain: false
    reportUnmatchedIgnoredErrors: true

NEON;
    }
}
