<?php

declare(strict_types=1);

namespace KaririCode\Devkit\Configuration;

use KaririCode\Devkit\Contract\ConfigGenerator;
use KaririCode\Devkit\Core\ProjectContext;

/**
 * Generates `.kcode/phpstan.neon`.
 *
 * @since 1.0.0
 */
final class PhpStanConfigGenerator implements ConfigGenerator
{
    #[\Override]
    public function toolName(): string
    {
        return 'phpstan';
    }

    #[\Override]
    public function outputPath(): string
    {
        return 'phpstan.neon';
    }

    #[\Override]
    public function generate(ProjectContext $context): string
    {
        $paths = implode("\n", array_map(
            static fn (string $d): string => "        - ../{$d}",
            $context->relativeSourceDirs(),
        ));

        $excludes = '';
        if ([] !== $context->excludeDirs) {
            $items = implode("\n", array_map(
                static fn (string $d): string => "        - ../{$d}",
                $context->excludeDirs,
            ));
            $excludes = <<<NEON

                    excludePaths:
                {$items}
                NEON;
        }

        return <<<NEON
            # Generated by KaririCode Devkit — override via devkit.php (project root)
            parameters:
                level: {$context->phpstanLevel}
                paths:
            {$paths}
            {$excludes}
                tmpDir: build/.phpstan
                checkMissingCallableSignature: true
                treatPhpDocTypesAsCertain: false
                reportUnmatchedIgnoredErrors: true

            NEON;
    }
}
