<?php

declare(strict_types=1);

namespace KaririCode\Devkit\Configuration;

use KaririCode\Devkit\Contract\ConfigGenerator;
use KaririCode\Devkit\Core\ProjectContext;

/**
 * Generates `.kcode/phpunit.xml.dist`.
 *
 * All caches and reports are routed to `.kcode/build/` to keep
 * the project root clean. Bootstrap points to `../vendor/autoload.php`
 * relative to the generated config location.
 *
 * @since 1.0.0
 */
final class PhpUnitConfigGenerator implements ConfigGenerator
{
    #[\Override]
    public function toolName(): string
    {
        return 'phpunit';
    }

    #[\Override]
    public function outputPath(): string
    {
        return 'phpunit.xml.dist';
    }

    #[\Override]
    public function generate(ProjectContext $context): string
    {
        $suites = $this->renderSuites($context);
        $sourceIncludes = $this->renderDirList($context->relativeSourceDirs(), 12);
        $coverageExcludes = $this->renderDirList($context->coverageExclude, 12);

        return <<<XML
            <?xml version="1.0" encoding="UTF-8"?>
            <!-- Generated by KaririCode Devkit — override via devkit.php (project root) -->
            <phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/12.5/phpunit.xsd"
                     bootstrap="../vendor/autoload.php"
                     cacheDirectory="build/.phpunit.cache"
                     executionOrder="depends,defects"
                     requireCoverageMetadata="false"
                     beStrictAboutCoverageMetadata="true"
                     beStrictAboutOutputDuringTests="true"
                     failOnRisky="true"
                     failOnWarning="true"
                     colors="true">

                <php>
                    <ini name="display_errors" value="1"/>
                    <ini name="error_reporting" value="-1"/>
                    <ini name="memory_limit" value="-1"/>
                    <env name="APP_ENV" value="testing"/>
                </php>

                <testsuites>
            {$suites}    </testsuites>

                <source restrictDeprecations="true" restrictNotices="true" restrictWarnings="true">
                    <include>
            {$sourceIncludes}        </include>
                    <exclude>
            {$coverageExcludes}        </exclude>
                </source>

                <coverage includeUncoveredFiles="true"
                          pathCoverage="false"
                          ignoreDeprecatedCodeUnits="true"
                          disableCodeCoverageIgnore="false">
                    <report>
                        <html outputDirectory="build/coverage"/>
                        <text outputFile="php://stdout" showUncoveredFiles="false"/>
                        <clover outputFile="build/clover.xml"/>
                    </report>
                </coverage>

                <logging>
                    <junit outputFile="build/junit.xml"/>
                </logging>
            </phpunit>

            XML;
    }

    private function renderSuites(ProjectContext $context): string
    {
        $xml = '';

        foreach ($context->testSuites as $name => $relativeDir) {
            $xml .= "        <testsuite name=\"{$name}\">\n";
            $xml .= "            <directory>../{$relativeDir}</directory>\n";
            $xml .= "        </testsuite>\n";
        }

        return $xml;
    }

    /** @param list<string> $dirs */
    private function renderDirList(array $dirs, int $indent): string
    {
        $pad = str_repeat(' ', $indent);
        $xml = '';

        foreach ($dirs as $dir) {
            $xml .= "{$pad}<directory>../{$dir}</directory>\n";
        }

        return $xml;
    }
}
