<?php

declare(strict_types=1);

namespace KaririCode\Devkit\Configuration;

use KaririCode\Devkit\Contract\ConfigGenerator;
use KaririCode\Devkit\Core\ProjectContext;

/**
 * Generates `.kcode/psalm.xml`.
 *
 * @since 1.0.0
 */
final class PsalmConfigGenerator implements ConfigGenerator
{
    public function toolName(): string
    {
        return 'psalm';
    }

    public function outputPath(): string
    {
        return 'psalm.xml';
    }

    public function generate(ProjectContext $context): string
    {
        $sourceDirs = '';

        foreach ($context->relativeSourceDirs() as $dir) {
            $sourceDirs .= "        <directory name=\"../{$dir}\" />\n";
        }

        return <<<XML
<?xml version="1.0"?>
<!-- Generated by KaririCode Devkit — override via devkit.php (project root) -->
<psalm
    errorLevel="{$context->psalmLevel}"
    resolveFromConfigFile="true"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="https://getpsalm.org/schema/config"
    xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
    cacheDirectory="build/.psalm"
    findUnusedBaselineEntry="true"
    findUnusedCode="false"
>
    <projectFiles>
{$sourceDirs}        <ignoreFiles>
            <directory name="../vendor" />
        </ignoreFiles>
    </projectFiles>
</psalm>

XML;
    }
}
