<?php

declare(strict_types=1);

namespace KaririCode\Devkit\Configuration;

use KaririCode\Devkit\Contract\ConfigGenerator;
use KaririCode\Devkit\Core\ProjectContext;
use Override;

/**
 * Generates `.kcode/rector.php` targeting PHP 8.4 quality sets.
 *
 * @since 1.0.0
 */
final class RectorConfigGenerator implements ConfigGenerator
{
    #[Override]
    public function toolName(): string
    {
        return 'rector';
    }

    #[Override]
    public function outputPath(): string
    {
        return 'rector.php';
    }

    #[Override]
    public function generate(ProjectContext $context): string
    {
        $paths = '';

        foreach ($context->relativeSourceDirs() as $dir) {
            $paths .= "        __DIR__ . '/../{$dir}',\n";
        }

        foreach ($context->relativeTestDirs() as $dir) {
            $paths .= "        __DIR__ . '/../{$dir}',\n";
        }

        $sets = $this->renderSets($context->rectorSets);

        return <<<PHP
            <?php

            declare(strict_types=1);

            /**
             * Generated by KaririCode Devkit — override via devkit.php (project root)
             * key: rector_sets (replaces KaririCode defaults).
             */

            use Rector\Config\RectorConfig;
            use Rector\Set\ValueObject\LevelSetList;
            use Rector\Set\ValueObject\SetList;

            return RectorConfig::configure()
                ->withPaths([
            {$paths}    ])
                ->withPhpSets(php84: true)
                ->withSets([
            {$sets}    ])
                ->withImportNames(
                    importShortClasses: false,
                    removeUnusedImports: true,
                );

            PHP;
    }

    /** @param list<string> $sets */
    private function renderSets(array $sets): string
    {
        $lines = '';

        foreach ($sets as $set) {
            $lines .= "        {$set},\n";
        }

        return $lines;
    }
}
